/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BotAssistant: typeof import('./src/components/BotAssistant.vue')['default']
    DialogBox: typeof import('./src/components/DialogBox.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    LuckyDraw: typeof import('./src/components/LuckyDraw.vue')['default']
    OrderPage: typeof import('./src/components/OrderPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheSideBar: typeof import('./src/components/TheSideBar.vue')['default']
    TheSiderBar: typeof import('./src/components/TheSiderBar.vue')['default']
    TheTest: typeof import('./src/components/TheTest.vue')['default']
  }
}
